id: PEB0A4E44
initial_creation_type: input
source_metadata:
  title: Kauśikapaddhati
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Vedāṅga -- Gṛhyasūtra
  data entry: Ketaki Gokhale
  contribution to GRETIL: Ketaki Gokhale
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:50:02.942066'
last_modified_at: '2022-03-09T14:50:02.942139'
